export const AuthErrorCode = {
  EMAIL_RATE_LIMITED: "EMAIL_RATE_LIMITED",
  VERIFICATION_COOLDOWN: "VERIFICATION_COOLDOWN",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  INVALID_SIGN_UP_TOKEN: "INVALID_SIGN_UP_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
} as const;

export const AttachmentErrorCode = {
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  ATTACHMENT_ALREADY_CONFIRMED: "ATTACHMENT_ALREADY_CONFIRMED",
  ATTACHMENT_NOT_UPLOADED: "ATTACHMENT_NOT_UPLOADED",
  ATTACHMENT_ALREADY_ASSOCIATED: "ATTACHMENT_ALREADY_ASSOCIATED",
} as const;

export const PaginationErrorCode = {
  INVALID_CURSOR: "INVALID_CURSOR",
} as const;

export const PostErrorCode = {
  POST_NOT_FOUND: "POST_NOT_FOUND",
  NOT_POST_AUTHOR: "NOT_POST_AUTHOR",
} as const;

export const CommentErrorCode = {
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  NOT_COMMENT_AUTHOR: "NOT_COMMENT_AUTHOR",
} as const;

export const ResourceErrorCode = {
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
} as const;

export const MissionErrorCode = {
  MISSION_NOT_FOUND: "MISSION_NOT_FOUND",
} as const;

export const MissionAssignmentErrorCode = {
  MISSION_ASSIGNMENT_NOT_FOUND: "MISSION_ASSIGNMENT_NOT_FOUND",
  MISSION_ASSIGNMENT_NOT_FOR_TODAY: "MISSION_ASSIGNMENT_NOT_FOR_TODAY",
  MISSION_ASSIGNMENT_ALREADY_COMPLETED: "MISSION_ASSIGNMENT_ALREADY_COMPLETED",
} as const;
